name: Auto Semantic Version Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: latest
        run: |
          git fetch --tags

          LATEST=$(git tag --sort=-v:version | head -n 1)

          if [ -z "$LATEST" ]; then
            LATEST="v0.0.0"
          fi

          echo "latest=$LATEST" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag ${{ steps.bump.outputs.new }}
          git push origin ${{ steps.bump.outputs.new }} #test